---
title: "earthquakes"
output:
  html_document: default
  pdf_document: default
date: "2024-01-25"
---

Install packages
```{r, warning=FALSE, results='hide', results='hide', message=FALSE}
pacotes <- c("dplyr","tidyverse","RColorBrewer", "ggplot2", "gplots", "lattice", "fields", "viridis", "corrplot", "htmltools", "htmlwidgets")
if(sum(as.numeric(!pacotes %in% installed.packages())) != 0){
  instalador <- pacotes[!pacotes %in% installed.packages()]
  for(i in 1:length(instalador)) {
    install.packages(instalador, dependencies = T)
    break()}
  sapply(pacotes, require, character = T) 
} else {
  sapply(pacotes, require, character = T) 
}

```

Data cleaning
```{r, results='hide', warning=FALSE,  message=FALSE}
df <- read_csv("earthquakes_2023_global.csv")
head(df)
str(df)
dim(df) # 26642 obs   22 col
colSums(is.na(df)) # NAs = nst; gap; dmin; plac; horizontal error; magerror, magnst
sum(is.na(df)) # total NAs 11104
sum(rowSums(is.na(df)) > 0) # number of obs with NAs = 3771
#df$nst # Number of seismic stations that reported the earthquake.
#df$gap # The gap between different seismic stations' coverage.
#df$dmin # Minimum distance to the earthquake epicenter for the nearest station.
#df$horizontalError #Horizontal error in location determination.
#df$magError #Error in magnitude determination.
#df$magNst #Number of seismic stations used to calculate the magnitude.
#3771/26642 = 0.1415434 - 15% of obs has null values, we will try first EDA by removing them all
colnames(df)

# Check outliers
lapply(names(df), function(col) {
  if (is.numeric(df[[col]])) {
    boxplot(df[[col]], main = col)
  }
})

df_cleaned <- na.omit(df) # remove obs with NAs
dim(df_cleaned) #22871 obs    22 col
head(df_cleaned)

```
Check magnitude distribution
```{r, warning=FALSE, message=FALSE}
ggplot(df_cleaned, aes(x = mag)) +
  geom_histogram(binwidth = 0.5, fill = "lightblue", color = "black", alpha = 0.7) +
  geom_density(aes(y = ..count..), color = "red", linetype = "dashed", size = 1, bw = 0.7) +
  labs(title = "Distribution of Earthquake Magnitudes",
       x = "Magnitude", y = "Frequency") +
  theme_minimal()
```

Calculate correlation matrix
```{r, warning=FALSE, message=FALSE}
# Select numeric columns
numeric_columns <- df_cleaned[, sapply(df_cleaned, is.numeric)]

correlation_matrix <- cor(numeric_columns)
correlation_matrix <- round(cor(numeric_columns), 2)
correlation_matrix

#correlation_matrix <- round(correlation_matrix, 2)
#correlation_matrix

corrplot(correlation_matrix, method="color")


```

Check magnitude of earthquakes around the world
```{r, message=FALSE, warning=FALSE}
color_palette <- leaflet::colorBin(palette = "RdYlBu", domain = df_cleaned$mag, bins = 5, reverse = TRUE)

# Create the Leaflet map
mymap <- leaflet::leaflet(df_cleaned) %>%
  leaflet::addTiles() %>%
  leaflet::addCircleMarkers(
    ~longitude, ~latitude,
    radius = ~sqrt(mag) * 3,  # Adjust the size based on magnitude
    color = ~color_palette(mag),
    fillOpacity = 0.7,  # Adjust the transparency of the circles
        popup = ~paste("Place: ", place, "<br>Magnitude: ", mag, "<br>Updated: ", updated)
  ) %>%
  leaflet::addLegend(
    position = "bottomright",
    pal = color_palette,
    values = ~mag,
    title = "Magnitude"
  ) 

# Create an HTML title
title_html <- tags$h2("Earthquake Magnitudes Worldwide in 2023")

# Display the map with the title
htmltools::tagList(title_html, mymap)

#saveWidget(mymap, file = "interactive_map.html")

```

